import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const a='00000000-0000-0000-0000-000000000001', b='00000000-0000-0000-0000-000000000002';
const q='10000000-0000-0000-0000-000000000001';
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create schema private;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table public.app_admins(user_id uuid primary key references auth.users);
create function private.is_app_admin() returns boolean language sql stable security definer as $$select exists(select 1 from public.app_admins where user_id=auth.uid())$$;
create table public.questions(id uuid primary key);
create table public.attempts(id uuid primary key);
create table public.notes(user_id uuid,question_id uuid,body_md text,unique(user_id,question_id));
grant usage on schema public,auth,private to anon,authenticated,service_role;
insert into auth.users values('${a}'),('${b}'); insert into app_admins values('${a}');insert into questions values('${q}');`);
await db.exec(await readFile(new URL('../supabase/migrations/20260916000000_ai_tutor.sql',import.meta.url),'utf8'));
const req=n=>`20000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const begin=n=>db.query(`select ai_begin($1,$2,'version',$3,'why','hint','model') as result`,[a,q,req(n)]);
const first=(await begin(1)).rows[0].result;
assert.equal(first.duplicate,false);
assert.equal((await begin(1)).rows[0].result.duplicate,true);
await assert.rejects(()=>begin(2),/generation_busy/);
await assert.rejects(()=>db.query('select ai_clear($1,$2)',[a,q]),/generation_busy/);
await db.exec(`update ai_messages set status='complete' where role='assistant';`);
for(let i=2;i<=10;i++){await begin(i);await db.exec(`update ai_messages set status='complete' where role='assistant';`);}
await assert.rejects(()=>begin(11),/rate_limit/);
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${b}',false);`);
assert.equal((await db.query('select * from ai_messages')).rows.length,0);
await assert.rejects(()=>db.query(`insert into ai_settings(user_id) values('${b}')`),/permission denied/);
await assert.rejects(()=>begin(12),/permission denied/);
await db.exec(`select set_config('request.jwt.claim.sub','${a}',false);`);
assert.equal((await db.query('select * from ai_messages')).rows.length,20);
await db.exec('reset role;');
await db.exec(`delete from app_admins;set role authenticated;`);
assert.equal((await db.query('select * from ai_messages')).rows.length,0);
await db.exec('reset role;set role anon;');
await assert.rejects(()=>db.query('select * from ai_settings'),/permission denied/);
await db.exec('reset role;');
assert.match((await db.query('select ai_append_note($1,$2,$3,$4) as body',[a,q,'new note',''])).rows[0].body,/new note/);
await assert.rejects(()=>db.query('select ai_append_note($1,$2,$3,$4)',[a,q,'overwrite','stale']),/note_conflict/);
assert.equal((await db.query('select * from notes')).rows.length,1);
await db.query('select ai_clear($1,$2)',[a,q]);
assert.equal((await db.query('select * from ai_messages')).rows.length,0);
assert.equal((await db.query('select * from notes')).rows.length,1);
assert.equal((await db.query(`select column_default from information_schema.columns where table_name='attempts' and column_name='assistance_used'`)).rows[0].column_default,null);
await db.close();console.log('PASS: SQL migration, idempotency, single-flight, 10/min, owner/admin RLS, revocation, append conflict, clear isolation, NULL legacy assistance');
