import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002',r='20000000-0000-0000-0000-000000000001';
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema private;
 create table auth.users(id uuid primary key);create table public.app_admins(user_id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function private.is_app_admin() returns boolean language sql stable security definer as $$select exists(select 1 from app_admins where user_id=auth.uid())$$;
 create table rates(user_id uuid);create function public.ai_take_rate(p_user uuid) returns void language sql as $$insert into rates values(p_user)$$;
 grant usage on schema public,auth,private to anon,authenticated,service_role;
 insert into auth.users values('${a}'),('${b}');insert into app_admins values('${a}');`);
await db.exec(await readFile(new URL('../supabase/migrations/20260919000000_concept_labs.sql',import.meta.url),'utf8'));
const begin=(id=r,lab='cpp-dispatch',user=a)=>db.query('select lab_begin($1,$2,1,$3,\'why\',\'synthetic\') as result',[user,lab,id]);
assert.equal((await begin()).rows[0].result.duplicate,false);
assert.equal((await begin()).rows[0].result.duplicate,true);
assert.equal((await db.query('select * from rates')).rows.length,1);
await assert.rejects(()=>begin(r,'gc-roots'),/request_context_conflict/);
await assert.rejects(()=>begin('20000000-0000-0000-0000-000000000002'),/generation_busy/);
await assert.rejects(()=>begin(r,'cpp-dispatch',b),/admin_required/);
await db.exec(`update lab_messages set status='complete',body='saved' where role='assistant';`);
assert.equal((await begin()).rows[0].result.message.body,'saved');
await db.exec(`insert into lab_runs values('${a}','${r}','cpp-dispatch',1,'{}',now());set role authenticated;select set_config('request.jwt.claim.sub','${b}',false);`);
assert.equal((await db.query('select * from lab_runs')).rows.length,0);assert.equal((await db.query('select * from lab_messages')).rows.length,0);
await assert.rejects(()=>begin(),/permission denied/);
await db.exec(`select set_config('request.jwt.claim.sub','${a}',false);`);assert.equal((await db.query('select * from lab_runs')).rows.length,1);
await assert.rejects(()=>db.exec('delete from lab_runs'),/permission denied/);
await db.exec('reset role;delete from app_admins;set role authenticated;');assert.equal((await db.query('select * from lab_messages')).rows.length,0);
await db.exec('reset role;set role anon;');await assert.rejects(()=>db.query('select * from lab_messages'),/permission denied/);
await db.close();console.log('PASS: lab migration, dedup, busy, admin revocation, ownership, anonymous denial, no client writes');
